repos:
  - repo: local
    hooks:
      - id: cogogitto
        name: Cogogitto
        entry: cog check --from-latest-tag
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.1
    hooks:
      - id: swiftlint
        entry: swiftlint --fix --strict
