from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = true
disable_bump_commit = true
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = true
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]
ci = { changelog_title = "", omit_from_changelog = true }
cd = { changelog_title = "", omit_from_changelog = true }
deps = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = [{ username = "jesse-c", signature = "Jesse Claven" }]

[bump_profiles]

[packages]
